"""empty message

Revision ID: 03674ee1c6e9
Revises: 9658ab9c7642
Create Date: 2021-08-24 10:55:19.062405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03674ee1c6e9'
down_revision = '9658ab9c7642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('favourites_client_id_fkey', 'favourites', type_='foreignkey')
    op.create_foreign_key(None, 'favourites', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.create_foreign_key('favourites_client_id_fkey', 'favourites', 'account', ['client_id'], ['id'])
    # ### end Alembic commands ###
