"""empty message

Revision ID: 1f84095e5f82
Revises: 38451ba36534
Create Date: 2021-08-24 14:33:45.696286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f84095e5f82'
down_revision = '38451ba36534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'client_id')
    # ### end Alembic commands ###
