"""empty message

Revision ID: 38451ba36534
Revises: 8f9faadf77b9
Create Date: 2021-08-24 14:28:37.101589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38451ba36534'
down_revision = '8f9faadf77b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_reviews_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_client_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'reviews_id')
    op.drop_column('comments', 'client_id')
    op.drop_constraint('reviews_services_id_fkey', 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'services_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('services_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reviews_services_id_fkey', 'reviews', 'services', ['services_id'], ['id'])
    op.add_column('comments', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('reviews_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_client_id_fkey', 'comments', 'client', ['client_id'], ['id'])
    op.create_foreign_key('comments_reviews_id_fkey', 'comments', 'reviews', ['reviews_id'], ['id'])
    # ### end Alembic commands ###
