"""empty message

Revision ID: 8f9faadf77b9
Revises: 03674ee1c6e9
Create Date: 2021-08-24 13:59:15.759726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9faadf77b9'
down_revision = '03674ee1c6e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_services',
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name='business_services_business_id_fkey'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='business_services_service_id_fkey'),
    sa.PrimaryKeyConstraint('business_id', 'service_id', name='business_services_pkey')
    )
    # ### end Alembic commands ###
