"""empty message

Revision ID: 9658ab9c7642
Revises: ea370ffaebce
Create Date: 2021-08-24 09:46:57.359559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9658ab9c7642'
down_revision = 'ea370ffaebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('is_client', sa.Boolean(create_constraint=True), nullable=False))
    op.drop_column('account', 'account_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('account_type', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('account', 'is_client')
    # ### end Alembic commands ###
