"""empty message

Revision ID: 98c93c933fde
Revises: 87d37d264b91
Create Date: 2021-08-22 13:17:17.298616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c93c933fde'
down_revision = '87d37d264b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourites', sa.Column('client_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favourites', 'account', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favourites', type_='foreignkey')
    op.drop_column('favourites', 'client_id')
    # ### end Alembic commands ###
