data = {

    "Services": [
        {
            "id": 1,
            "title": "Arts"
        },
        {
            "id": 2,
            "title": "Healthcare"
        },
        {
            "id": 3,
            "title": "Languages"
        },
        {
            "id": 4,
            "title": "Meditation"
        },
        {
            "id": 5,
            "title": "Meetings"
        },
        {
            "id": 6,
            "title": "Psychology"
        },
        {
            "id": 7,
            "title": "Sports"
        },
    ],
    "Account": [
        {
            "id": 1,
            "is_client": False,
            "email": "arts@okage.es",
            "_password": "123456",
            "phone": "633445566",
            "name": "Muay",
            "last_name": "Thai",
            "province": "Madrid",
            "post_code": "28019",
            "adress": "C/ Nicolás Morales 24",
            "profile_foto": "photo",
            "_is_active": True
        },
        {
            "id": 2,
            "is_client": False,
            "email": "healthcare@okage.es",
            "_password": "123456",
            "phone": "644556677",
            "name": "Florence",
            "last_name": "Paloma",
            "province": "Madrid",
            "post_code": "28022",
            "adress": "C/ Arturo Soria 37",
            "profile_foto": "photo",
            "_is_active": True
        },
        {
            "id": 3,
            "is_client": False,
            "email": "languages@okage.es",
            "_password": "123456",
            "phone": "655667788",
            "name": "Ricardo",
            "last_name": "Rosario",
            "province": "Madrid",
            "post_code": "28004",
            "adress": "C/ Valgame Dios 16",
            "profile_foto": "photo",
            "_is_active": True
        },
        {
            "id": 4,
            "is_client": False,
            "email": "meetings@okage.es",
            "_password": "123456",
            "phone": "666778899",
            "name": "Vinolia",
            "last_name": "Barreto",
            "province": "Barcelona",
            "post_code": "08001",
            "adress": "C/ Mare de Deu 57",
            "profile_foto": "photo",
            "_is_active": True
        },
        {
            "id": 5,
            "is_client": False,
            "email": "psychology@okage.es",
            "_password": "123456",
            "phone": "677889900",
            "name": "Ruben",
            "last_name": "Perez",
            "province": "Barcelona",
            "post_code": "08002",
            "adress": "C/ Jaume I 89",
            "profile_foto": "photo",
            "_is_active": True
        },
        {
            "id": 6,
            "is_client": False,
            "email": "sports@okage.es",
            "_password": "123456",
            "phone": "688990011",
            "name": "Jimena",
            "last_name": "Escobar",
            "province": "Madrid",
            "post_code": "28012",
            "adress": "C/ Las Divinas 36",
            "profile_foto": "photo",
            "_is_active": True
        },
    ],
    "Business": [
        {
            "id": 1,
            "account_id": 1,
            "centre_name": "ISEP Clinic",
            "cif": "https://cdn.dribbble.com/users/690037/screenshots/15321173/media/3110c5335303dd9270607ca752969dd1.jpg",
            "schedule": "Mon–Fri from 9:00–21:00"
        },
        {
            "id": 2,
            "account_id": 2,
            "centre_name": "Verywell Health Group",
            "cif": "https://cdn.dribbble.com/users/1469094/screenshots/14664812/media/8a4dc388f42abca80f971af836bb76a2.png? compress=1&resize=1600x1200",
            "schedule": "Fri-Sat from 10:00–14:00"
        },
        {
            "id": 3,
            "account_id": 3,
            "centre_name": "Paloma's Lifestyle",
            "cif": "https://cdn.dribbble.com/users/690037/screenshots/4605155/media/a934b5b92cea141470fb58d81e98942c.jpg",
            "schedule": "Tuesdays from 18:00–20:00"
        },
        {
            "id": 4,
            "account_id": 4,
            "centre_name": "Javier Botella's Clinic",
            "cif": "https://cdn.dribbble.com/users/1700393/screenshots/15896914/media/9e54a6026545d1493d9e9decf71f6677.png",
            "schedule": "Mon-Fri from 9:00–22:00"
        },
        {
            "id": 5,
            "account_id": 5,
            "centre_name": "Rainbow of Smiles",
            "cif": "https://cdn.dribbble.com/users/271258/screenshots/4775105/media/66fe43be1f5a938d73f188eecafde203.jpg",
            "schedule": "Thursdays at 20:00"
        },
        {
            "id": 6,
            "account_id": 6,
            "centre_name": "Umbridge's Academy",
            "cif": "https://cdn.dribbble.com/users/4529799/screenshots/14430076/media/39e08750bbf74be927cccba24e73b2f7.png",
            "schedule": "Mon-Wed from 10:00–14:00"
        },
    ],

    "Buservices": [
        {
            "id": 1,
            "business_id": 1,
            "services_id": 6,
            "phone": "633445566",
            "email": "isep@clinic.com",
            "title_bus": "ISEP Clinic Madrid",
            "professional_name": "Sandra Muñoz Revilla",
            "professional_studies": "Degree in Psychology.",
            "professional_techniques": "https://images.pexels.com/photos/4098274/pexels-photo-4098274.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress": "Calle de Maldonado, 29, 28006 Madrid",
            "specialty": "Psychology",
            "numero_colegiado": "M–25869",
            "description": "Here at ISEP Clinic we are proud to be specialized in counseling, evaluation and treatment of emotional, learning and health problems of our dearly beloved patients. A task that we began in 1982 with the opening of our first office in Barcelona. Today, we are the largest network of psychological, psychopedagogical and speech therapy centers. Thanks to multidisciplinary care, we carry out personalized treatments for each of our patients in all areas that affect a better quality of life. Once the problem situation and the external and internal factors that influence it have been detected and analyzed, the steps to be taken to overcome it are proposed, from the framework of a continuous learning process.",
            "tecniques": "https://i.ibb.co/pZ6169w/2.png",
            "photos": "https://i.ibb.co/V3h15xt/3.png",
        },
        {
            "id": 2,
            "business_id": 1,
            "services_id": 1,
            "phone": "633445566",
            "email": "isep@clinic.com",
            "title_bus": "Therapeutic Painting for Children",
            "professional_name":"Marta Múgica Carrasco",
            "professional_studies": "Master in Clinical Psychology",
            "professional_techniques": "https://images.unsplash.com/photo-1607746882042-944635dfe10e? ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2850&q=80",
            "offer": False,
            "adress": "Calle de Maldonado, 29, 28006 Madrid",
            "specialty": "Arts",
            "numero_colegiado": "M–64513",
            "description": "When was the last time you picked up a paintbrush or a colored pencil? Maybe it’s been a while, but what about the last time you doodled on your notebook during a meeting? For many of us, when we think of art, we tend to think it’s not for us. Perhaps you think you aren’t very creative, but there’s more to it than merely being ‘good at drawing.’ Allowing our brains the freedom for free expression, even by doodling, can have a wonderful impact on how we process, retain, and share information. It’s no surprise that the therapy community has taken note of this, and in more recent years, there’s been a rise in the number of practitioners offering a very distinct form of therapy: art therapy.",
            "tecniques": "https://i.ibb.co/0tCt8Rm/1.png",
            "photos": "https://i.ibb.co/VwG6H70/2.png"
        },
        {
            "id": 3,
            "business_id": 2,
            "services_id": 7,
            "phone": "644556677",
            "email": "verywell@health.com",
            "title_bus": "Soccer Club",
            "professional_name": "Jorge Aurelio Patiño",
            "professional_studies": "Master in Intervention in Learning.",
            "professional_techniques": "https://images.pexels.com/photos/4098353/pexels-photo-4098353.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress": "Calle de Jesús del Valle, 23, 28004 Madrid",
            "specialty": "Sports",
            "numero_colegiado": "M–14859",
            "description": "To teach children soccer skills in a supportive environment, develop a life-long love of exercise, and to have FUN! Through Autism Soccer (AS), children learn that with training, confidence and love anything is possible. All our operating costs are covered by private donors so 100% of your donation goes directly to our projects and the services they provide to the children. What can you do to help? Just about anything! Run a race, plan a fundraising party, do a school project, bake some cakes. Everyone can help. We are always really happy to hear from people who want to volunteer time and skills. You can help us do more, and even work directly with the children.",
            "tecniques": "https://i.ibb.co/6nkCcss/3.png",
            "photos": "https://i.ibb.co/DVWgGZ9/4.png"
        },
        {
            "id": 4,
            "business_id": 2,
            "services_id": 7,
            "phone": "644556677",
            "email": "sports@okage.es",
            "title_bus": "Swimming Weekends",
            "professional_name": "Erika Gleeson",
            "professional_studies": "B.A Behavioural Science.",
            "professional_techniques":"https://images.pexels.com/photos/4098345/pexels-photo-4098345.jpeg? auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
            "offer": False,
            "adress": "Calle de Santa Clarita, 69, 2819 Madrid",
            "specialty": "Sports",
            "numero_colegiado": "M–23593",
            "description": "Swimming Weekends by Verywell Health was established in 2016 by Founder and Clinical Director Erika Gleeson (G.C Autism, B.A Behavioural Science). Erika is a Senior Behaviour and Skill Development Specialist in Autism Spectrum Disorder (ASD) and cognitive deficit; and is widely recognised as Australia’s leading expert in Wandering and Drowning prevention for those with ASD/cognitive deficit. Autism Swim is an international, multi-disciplinary organisation, combining the expertise of Autism Specialists, Behaviour Specialists, Occupational Therapists and Swimming Instructors to achieve the best possible outcomes for the individuals whom they support. Autism Swim also operates under the skilled leadership of an Advisory Board.",
            "tecniques": "https://i.ibb.co/QjdDFGf/5.png",
            "photos":"https://i.ibb.co/zNWXzx4/6.png"
        },
        {
            "id": 5,
            "business_id": 3,
            "services_id": 4,
            "phone": "655667788",
            "email": "florence@paloma.life",
            "title_bus": "Introduction to Meditation",
            "professional_name": "Florence Paloma",
            "professional_studies": "University of Salamanca.",
            "professional_techniques": "https://images.pexels.com/photos/7579116/pexels-photo-7579116.jpeg? auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
            "offer": False,
            "adress":"Calle de la Mamma Mía, 21, 20819 Madrid",
            "specialty": "Meditation",
            "numero_colegiado": "M–14743",
            "description": "Many parents of kids with ASD are turning to meditation, hoping it will help their kids with symptoms like anxiety, depression, difficulty sleeping, focus, repetitive thoughts and self-regulation. Research into the benefits is promising. In one study, parents of kids along the spectrum participated in an eight-week mindfulness program, then taught it to their children. Adults had improvements in the areas of parenting stress and family quality of life, and kids had reduced problem behaviours. A number of other studies show practicing mindfulness leads to lowered anxiety and thought problems in kids with ASD, plus social responsiveness, and less aggression in adolescents.",
            "tecniques":"https://i.ibb.co/Dwsz6S8/8.png",
            "photos":"https://i.ibb.co/P6mb7S6/7.png"
        },
        {
            "id": 6,
            "business_id": 4,
            "services_id": 2,
            "phone": "666778899",
            "email": "botella@clinic.com",
            "title_bus": "Intensive Preschool ABA Services",
            "professional_name":"Javier Botella",
            "professional_studies": "Senior Consultant of the Psychiatry Service and Coordinator of the Hospitalization Unit of Acute Hospital Ramón y Cajal.",
            "professional_techniques":"https://images.pexels.com/photos/4100672/pexels-photo-4100672.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress":"Calle de Estamos Bien, 34, 24018 Madrid",
            "specialty": "Healthcare",
            "numero_colegiado": "M–20763",
            "description":"With some children, the signs of autism might not become entirely obvious until they reach preschool (or even school age), when suddenly the developmental gap between them and their peers becomes more pronounced. In addition to the signs for babies/toddlers, here are some of the more common ways ASD might present itself in a preschool-aged child. When your child is diagnosed with autism spectrum disorder, there's a lot to learn. You're faced with new terms like 'early intervention' and 'positive behavior support.' It's normal to feel overwhelmed. But don't worry — you're not alone. Many parents have walked this path before. Many resources and support services are available to you.",
            "tecniques": "https://i.ibb.co/GpbPgjX/9.png",
            "photos": "https://i.ibb.co/WD6txt0/10.png"
        },
        {
            "id": 7,
            "business_id": 4,
            "services_id": 2,
            "phone": "666778899",
            "email": "botella@clinic.com",
            "title_bus": "Diagnostic for Children and Adults",
            "professional_name":"Javier Botella",
            "professional_studies":"Senior Consultant the Psychiatry Service.",
            "professional_techniques":"https://images.pexels.com/photos/4100672/pexels-photo-4100672.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress":"Calle de Estamos Bien, 34, 24018 Madrid",
            "specialty": "Healthcare",
            "numero_colegiado":"M–20763",
            "description":"Developmental screening can be done by a number of professionals in health care, community, and school settings. However, primary health care providers are in a unique position to promote children’s developmental health. Primary care providers have regular contact with children before they reach school age and are able to provide family-centered, comprehensive, coordinated care, including a more complete medical assessment when a screening indicates a child is at risk for a developmental problem. Additional screening might be needed if a child is at high risk for developmental problems because of preterm birth or low birth weight.",
            "tecniques":"https://i.ibb.co/GpbPgjX/9.png",
            "photos":"https://i.ibb.co/bFwx0x8/11.png",
        },
        {
            "id": 8,
            "business_id": 5,
            "services_id": 3,
            "phone": "677889900",
            "email": "rainbow@of.smiles",
            "title_bus": "English Trivia Nights",
            "professional_name":"Ernesto Feliz",
            "professional_studies":"Master in Cognitive Behavioral Psychotherapy.",
            "professional_techniques": "https://images.pexels.com/photos/6325954/pexels-photo-6325954.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress":"“La Central”, Plaza de Callao, 4, 28004 Madrid",
            "specialty": "Languages",
            "numero_colegiado": "M–57760",
            "description":"Let’s make new friends! A long-time staple among Madrid’s expat community, this corner bar has a downstairs bookstore selling a large selection of primarily used English-language books, including ESL resources. Up at the bar, you can get craft beer, wine, coffee, bagels and other things to munch on. Also check out J&J’s free events, including language exchanges and pub quizzes (trivia nights). Lots of fun! There’s something about drinking coffee or wine amidst a sea of books that makes me feel right at home. Whether you’re looking for the perfect place to enjoy a quiet conversation or a good read.",
            "tecniques":"https://i.ibb.co/tZMCy1S/14.png",
            "photos":"https://i.ibb.co/wdMnXwQ/15.png",
        },
        {
            "id": 9,
            "business_id": 5,
            "services_id": 5,
            "phone": "677889900",
            "email": "languages@okage.es",
            "title_bus": "Speed Friending",
            "professional_name":"Ernesto Feliz",
            "professional_studies": "Master in Cognitive Behavioral Psychotherapy.",
            "professional_techniques":"https://images.pexels.com/photos/6325954/pexels-photo-6325954.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress":"“Sky Dawson Café”, Calle Pez, 10, 28004 Madrid",
            "specialty": "Meetings",
            "numero_colegiado":"M–57760",
            "description":"No more lonely hearts. We understand how hard it can be for certain people to make friends. You get a conversation starting question to get the juices flowing, and seven minutes to get to know each other better. Studies show that 60% of people meet again after the event. We moved the social arenas into digital surfaces. Collaborating with a number of student organizations we made the study period during the pandemic a little more social. For several years we dreamed of creating a social app that allows people to get in touch with each other more easily, also regardless of our events. The app is currently in private beta testing, and will soon be available on your device.",
            "tecniques": "https://i.ibb.co/wM4ZRnh/16.png",
            "photos":"https://i.ibb.co/XJfymr3/17.png",
        },
        {
            "id": 10,
            "business_id": 6,
            "services_id": 3,
            "phone": "688990011",
            "email": "unbridge@academy.com",
            "title_bus": "French Catch Up!",
            "professional_name":"Dolores Umbridge",
            "professional_studies": "Postgraduate Specialist in Individual Psychodynamic.",
            "professional_techniques":"https://images.pexels.com/photos/5212325/pexels-photo-5212325.jpeg? auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
            "offer": False,
            "adress":"Calle de la Elocuencia, 2, 20018 Madrid",
            "specialty": "Languages",
            "numero_colegiado": "M–27663",
            "description":"I work in Ruchill Autism Unit as a class teacher and would like to relate the experience of introducing French into our pupils’ curriculum over the course of a school year. Ruchill Autism Unit is one of four Autism units which serves one of four geographical sectors in the City of Glasgow and is run by Glasgow City Education Department. It shares a campus with Ruchill Primary School and at present has a school roll of twenty four pupils, five teaching staff and seven Pupil Support Assistants. Children attending the unit have a diagnosis of an autism spectrum disorder, the implications of which are well documented and Greater Glasgow Health Board.",
            "tecniques": "https://i.ibb.co/ZKyc1LZ/13.png",
            "photos": "https://i.ibb.co/8Xb3zw8/12.png"
        },
    ],

}